excludes = ["COPYRIGHT", "LICENSE"]

[formatter.mdformat]
command = "mdformat"
excludes = []
includes = ["*.md"]
options = []

[formatter.nixfmt-rfc-style]
command = "nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[formatter.shfmt]
command = "shfmt"
options = ["-i", "2", "-s", "-w"]
includes = ["*.sh"]

[formatter.yamlfmt]
command = "yamlfmt"
excludes = []
includes = ["*.yaml", "*.yml"]
options = []
